### ISSUE TITLE
How the time changes by changing the number of threads 

### ISSUE THREAD

**Issue by usamaadev** [BilalAhmed-358/Parallel-and-Distributed-Computing-Project#1]
I increase the number of threads and time also increases why?

 ./final_file 200 100 8
Time take to parallely calculate convolution of the matrix using 8 threads is 0.2202 seconds.

./final_file 200 100 2
Time take to parallely calculate convolution of the matrix using 2 threads is 0.1096 seconds.

=========================================

./final_file 1000 50 8
Time take to parallely calculate convolution of the matrix using 8 threads is 5.4820 seconds.

./final_file 1000 50 2
Time take to parallely calculate convolution of the matrix using 2 threads is 2.3609 seconds.

**Comment by BilalAhmed-358** [comment]
# Introduction

This program will work properly, only when you give it 8 threads.

I have written the code such that 2 threads work on each quadrant of the matrix

For example:
1. Thread **0 and 1** will work on the **first quadrant**
1. Thread **2 and 3** will work on the **second quadrant**
   
and so on...
## Code Example

You can see this in the code on `line 111` of the *final_file.cpp* file.

I am also copying the code snippet for better understanding over here.

```cpp
if (omp_get_thread_num() == 0 || omp_get_thread_num() == 1)
        {
#pragma omp parallel for schedule(dynamic)
            for (i = 0; i < middle_filter; i++)
            {

                for (j = 0; j < middle_filter; j++)
                {
                    sum = 0, count = 0;
                    for (p = 0; p < filter_size; p++)
                    {
                        for (q = 0; q < filter_size; q++)
                        {
                            count++;
                            sum += filter[p][q] * matrix_o[p + i][q + j];
                        }
                    }
                    convolution_matrix[i][j] = sum / count;
                }
            }
        }
```

The above code calculates the convolution of the first quadrant of the matrix only.
## Local Results

I have also saved the local results of each 2 threads in separate files:

1. `thread0and1.txt` file contains the result of the first quadrant calculated by thread 0 and 1.
2. `thread2and3.txt` file contains the result of the second quadrant calculated by thread 2 and 3.
3. `thread4and5.txt` file contains the result of the third quadrant calculated by thread 4 and 5.
4. `thread6and7.txt` file contains the result of the fourth quadrant calculated by thread 6 and 7.

Similarly, on `line number 148` you can see that I used **thread number 2 and 3** for doing calculations on the second quadrant

```cpp
if (omp_get_thread_num() == 2 || omp_get_thread_num() == 3)
```

# Conclusion

Now on to your primary question, **How the time changes by changing the number of threads?**

# Answer

Well the answer is pretty self-explanatory, when you give the program **2 threads** only, it will calculate the results of the **first quadrant** only. 

Thus it takes less time. You can also verify it using the local results saved in files

1. `thread0and1.txt`
2. `thread2and3.txt`
2. `thread4and5.txt`
2. `thread6and7.txt`

When you run `./final_file 200 100 8` in your terminal, all files will save their local results in them, and the combined result will be saved in the `ConvolutionMatrix.txt` file.

***BUT!*** when you run the `./final_file 200 100 2` command from your terminal, only
1. `thread0and1.txt`

will contain results while the rest of the files 

1. `thread2and3.txt`
1. `thread4and5.txt`
1. `thread6and7.txt`

will be empty, and the `ConvolutionMatrix.txt` file will also contain only results of the first quadrant and not the complete matrix.

This is the reason the program takes less time when you give it 2 threads because its doing only 1/4th of the work its supposed to do.

I hope you find this answer helpful.
